"""
Ground truth SAR label assignment.

This module is the single location where ``Alert.true_sar`` is set.
It runs AFTER all transactions are generated and AFTER all alerts are created.

Ground truth rule (from design spec):
  alert.true_sar = (
      account.risk_category == AccountRiskCategory.ACTIVE_ML
      AND alert.triggered_by_typology_txn
  )

The rule is intentionally conservative:
  * ACTIVE_ML accounts that generate alerts on routine (non-typology)
    transactions are false positives — the account is ML-active but the
    specific alert was not triggered by a typology transaction.
  * Non-ACTIVE_ML accounts are always false positives regardless of which
    rule triggered.

This mirrors real-world SAR filing: an analyst investigates a specific
alert and files a SAR only when the evidence in that alert links to the
suspected typology behaviour.

Calling order in runner.py:
  1. generate transactions (including typology flag setting)
  2. evaluate TMS rules → alerts (triggered_by_typology_txn set here)
  3. call assign_ground_truth() ← this module
  4. compute features
"""

from __future__ import annotations

from .entities import Account, AccountRiskCategory, Alert


def assign_ground_truth(
    alerts: list[Alert],
    account_map: dict[str, Account],
) -> None:
    """Set ``Alert.true_sar`` for every alert in-place.

    Args:
        alerts: All alerts generated by the TMS engine.
        account_map: Maps account_id → Account.

    Raises:
        ValueError: If an account referenced by an alert is not in account_map.
        ValueError: If any alert already has true_sar set (calling order violation).
    """
    for alert in alerts:
        if alert.true_sar is not None:
            raise ValueError(
                f"Alert {alert.alert_id}: true_sar already set to {alert.true_sar}. "
                f"assign_ground_truth() must be called exactly once after alert creation."
            )

        account = account_map.get(alert.account_id)
        if account is None:
            raise ValueError(
                f"Alert {alert.alert_id}: account {alert.account_id} not found "
                f"in account_map. Ensure account_map covers all alerted accounts."
            )

        alert.true_sar = (
            account.risk_category == AccountRiskCategory.ACTIVE_ML
            and alert.triggered_by_typology_txn
        )


def verify_ground_truth_integrity(
    alerts: list[Alert],
    account_map: dict[str, Account],
) -> list[str]:
    """Run post-assignment integrity checks.  Returns list of error messages.

    An empty list means all checks passed.
    """
    errors: list[str] = []

    for alert in alerts:
        if alert.true_sar is None:
            errors.append(
                f"Alert {alert.alert_id}: true_sar is None after assignment"
            )
            continue

        account = account_map.get(alert.account_id)
        if account is None:
            errors.append(f"Alert {alert.alert_id}: missing account")
            continue

        is_active_ml = account.risk_category == AccountRiskCategory.ACTIVE_ML

        # Check 1: A non-ACTIVE_ML account cannot have true_sar=True
        if alert.true_sar and not is_active_ml:
            errors.append(
                f"Alert {alert.alert_id}: true_sar=True but account is "
                f"{account.risk_category.value}, not ACTIVE_ML"
            )

        # Check 2: A true SAR must have triggered_by_typology_txn=True
        if alert.true_sar and not alert.triggered_by_typology_txn:
            errors.append(
                f"Alert {alert.alert_id}: true_sar=True but "
                f"triggered_by_typology_txn=False"
            )

        # Check 3: triggered_by_typology_txn on a non-ACTIVE_ML account
        # is a data-integrity violation (typologies only run on ACTIVE_ML)
        if alert.triggered_by_typology_txn and not is_active_ml:
            errors.append(
                f"Alert {alert.alert_id}: triggered_by_typology_txn=True but "
                f"account is not ACTIVE_ML (account_type={account.risk_category.value})"
            )

    return errors
